const fs = require('fs');
const path = require('path');

const SKIP_PATTERNS = [
  /node_modules/,
  /\.git[\\/]/,
  /dist[\\/]/,
  /build[\\/]/,
  /\.next[\\/]/,
  /__pycache__[\\/]/,
  /\.vscode[\\/]/,
  /\.idea[\\/]/,
  /coverage[\\/]/,
  /build[\\/]/,
];

function shouldSkipFile(filePath, ignorePatterns) {
  const normalizedPath = filePath.replace(/\\/g, '/');
  return SKIP_PATTERNS.some(pattern => pattern.test(normalizedPath)) ||
         ignorePatterns.some(p => normalizedPath.includes(p));
}

function readFileContent(filePath) {
  try {
    const content = fs.readFileSync(filePath, 'utf-8');
    return content;
  } catch (error) {
    return null;
  }
}

function getLanguageFromExt(ext) {
  const extMap = {
    '.js': 'javascript',
    '.ts': 'typescript',
    '.jsx': 'jsx',
    '.tsx': 'tsx',
    '.py': 'python',
    '.java': 'java',
    '.c': 'c',
    '.cpp': 'cpp',
    '.h': 'c',
    '.hpp': 'cpp',
    '.go': 'go',
    '.rs': 'rust',
    '.rb': 'ruby',
    '.php': 'php',
    '.html': 'html',
    '.css': 'css',
    '.scss': 'scss',
    '.json': 'json',
    '.yaml': 'yaml',
    '.yml': 'yaml',
    '.toml': 'toml',
    '.md': 'markdown',
    '.txt': 'text',
    '.sh': 'bash',
    '.bash': 'bash',
    '.zsh': 'bash',
    '.sql': 'sql',
    '.graphql': 'graphql',
    '.gql': 'graphql',
    '.vue': 'vue',
    '.svelte': 'svelte',
  };
  return extMap[ext.toLowerCase()] || '';
}

function generateSMD(sourcePath, outputPath, options = {}) {
  const extensions = options.extensions || [
    'js', 'ts', 'jsx', 'tsx', 'py', 'java', 'c', 'cpp', 'go', 'rs',
    'rb', 'php', 'html', 'css', 'json', 'yaml', 'yml', 'toml', 'md', 'txt'
  ];
  const ignorePatterns = options.ignore || [];

  if (!fs.existsSync(sourcePath)) {
    throw new Error(`Source folder not found: ${sourcePath}`);
  }

  const stats = fs.statSync(sourcePath);
  if (!stats.isDirectory()) {
    throw new Error(`Source path is not a directory: ${sourcePath}`);
  }

  let markdown = `# Code Documentation\n\n`;
  markdown += `> Auto-generated by [smd](https://www.npmjs.com/package/smd-code-agent)\n`;
  markdown += `> Generated on: ${new Date().toISOString()}\n\n`;
  markdown += `## Table of Contents\n\n`;

  const files = [];
  const dirQueue = [sourcePath];

  while (dirQueue.length > 0) {
    const currentDir = dirQueue.shift();
    const entries = fs.readdirSync(currentDir, { withFileTypes: true });

    for (const entry of entries) {
      const fullPath = path.join(currentDir, entry.name);
      const relativePath = path.relative(sourcePath, fullPath);

      if (entry.isDirectory()) {
        if (!shouldSkipFile(fullPath, ignorePatterns)) {
          dirQueue.push(fullPath);
        }
        continue;
      }

      const ext = path.extname(entry.name).toLowerCase().slice(1);
      if (!extensions.includes(ext)) continue;
      if (shouldSkipFile(fullPath, ignorePatterns)) continue;

      const content = readFileContent(fullPath);
      if (content === null) continue;

      files.push({ relativePath, fullPath, content, ext });
    }
  }

  files.sort((a, b) => a.relativePath.localeCompare(b.relativePath));

  for (const file of files) {
    const anchor = file.relativePath.replace(/[^\w]/g, '-').toLowerCase();
    markdown += `- [${file.relativePath}](#${anchor})\n`;
  }

  markdown += `\n---\n\n## Files\n\n`;

  for (const file of files) {
    const lang = getLanguageFromExt(`.${file.ext}`);
    const contentPreview = file.content.trim();
    const lineCount = file.content.split('\n').length;

    markdown += `### ${file.relativePath}\n\n`;
    markdown += `> Lines: ${lineCount}\n\n`;
    markdown += `\`\`\`${lang}\n${contentPreview}\n\`\`\`\n\n`;
    markdown += `---\n\n`;
  }

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, markdown, 'utf-8');

  console.log(`✅ Generated ${outputPath}`);
  console.log(`📁 Source: ${sourcePath}`);
  console.log(`📄 Files: ${files.length}`);
  console.log(`📝 Output: ${(fs.statSync(outputPath).size / 1024).toFixed(2)} KB`);
}

module.exports = { generateSMD };
